name: python-actions
# on: push
on:
  pull_request:
    types: [opened, synchronize]
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6.10'

      - name: run unit test
        run: |
          cd app
          pip install pipenv
          pipenv install
          python -m unittest discover ./test/unit_test
          ls -la

      - name: run integration test
        run: docker-compose run --rm hoge python --version
